version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: besu-postgres
    environment:
      POSTGRES_DB: besu_contracts
      POSTGRES_USER: besu_user
      POSTGRES_PASSWORD: besu_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - besu_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U besu_user -d besu_contracts"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: besu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@besu.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - besu_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  besu_network:
    external: true
